[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
env_files = [".env.template"]
addopts = "--reuse-db"
filterwarnings = [
  "error",
]

[project]
name = "sppnaut"
version = "0.1"

[tool.setuptools]
packages = []
